# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatFriend.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 606)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(216, 250, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.firend_list = QtWidgets.QListWidget(self.centralwidget)
        self.firend_list.setGeometry(QtCore.QRect(10, 60, 260, 481))
        self.firend_list.setStyleSheet("QListWidget\n"
"{\n"
"    color:rgb(200,200,200);\n"
"    border:2px solid gray;\n"
"  \n"
"}\n"
"/**列表项*/\n"
"QListWidget::item\n"
"{\n"
"    color:rgb(200,100,200);\n"
"    height:40px;\n"
"    padding-left:20px;\n"
"    border:0px solid gray;\n"
"}\n"
"/**列表项扫过*/\n"
"QListWidget::item:hover\n"
"{\n"
"    color:rgb(235,225,255);\n"
"   \n"
"}\n"
"/**列表项选中*/\n"
"QListWidget::item::selected:active\n"
"{ \n"
"    color:black;\n"
"    border-width:0;\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    color:green;\n"
"    border-width:0;\n"
"}\n"
"")
        self.firend_list.setObjectName("firend_list")
        item = QtWidgets.QListWidgetItem()
        self.firend_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.firend_list.addItem(item)
        self.all_chat_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.all_chat_text.setGeometry(QtCore.QRect(290, 80, 551, 321))
        self.all_chat_text.setStyleSheet("border:1px solid blue;")
        self.all_chat_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.all_chat_text.setObjectName("all_chat_text")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(270, 0, 20, 541))
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 72, 15))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 9pt \"楷体\";")
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(280, 23, 731, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.add_friend_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_friend_button.setGeometry(QtCore.QRect(290, 10, 121, 28))
        self.add_friend_button.setStyleSheet("QPushButton{\n"
"    padding: 5px 25px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    color: #616161;\n"
"    font-weight: bold;\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    \n"
"    \n"
"}\n"
"QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
"    border: 2px solid transparent;\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
"    \n"
"    color: rgb(255, 79, 147);\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
"    color: #aeaeae;\n"
"    background-color:grey;\n"
"}")
        self.add_friend_button.setObjectName("add_friend_button")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(730, 420, 100, 40))
        self.send_button.setStyleSheet("QPushButton{\n"
"    padding: 5px 25px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    color: #616161;\n"
"    font-weight: bold;\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    \n"
"    \n"
"}\n"
"QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
"    border: 2px solid transparent;\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
"    \n"
"    color: rgb(255, 79, 147);\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
"    color: #aeaeae;\n"
"    background-color:grey;\n"
"}")
        self.send_button.setObjectName("send_button")
        self.chat_data_text = QtWidgets.QTextEdit(self.centralwidget)
        self.chat_data_text.setGeometry(QtCore.QRect(290, 420, 421, 40))
        self.chat_data_text.setStyleSheet("QTextEdit {\n"
"    border: 1px solid #A0A0A0; /* 边框宽度为1px，颜色为#A0A0A0 */\n"
"    border-radius: 5px; /* 边框圆角 */\n"
"    padding-left: 5px; /* 文本距离左边界有5px */\n"
"    background-color: #F2F2F2; /* 背景颜色 */\n"
"    color: #A0A0A0; /* 文本颜色 */\n"
"    selection-background-color: #A0A0A0; /* 选中文本的背景颜色 */\n"
"    selection-color: #F2F2F2; /* 选中文本的颜色 */\n"
"    font-family: \"Microsoft YaHei\"; /* 文本字体族 */\n"
"    font-size: 10pt; /* 文本字体大小 */\n"
"}\n"
"\n"
"QTextEdit:hover { /* 鼠标悬浮在QLineEdit时的状态 */\n"
"    border: 2px solid #298DFF;\n"
"    border-radius: 5px;\n"
"    background-color: #F2F2F2;\n"
"    color: #298DFF;\n"
"    selection-background-color: #298DFF;\n"
"    selection-color: #F2F2F2;\n"
"}\n"
"\n"
"QTextEdit[echoMode=\"2\"] { /* QLineEdit有输入掩码时的状态 */\n"
"    lineedit-password-character: 9679;\n"
"    lineedit-password-mask-delay: 2000;\n"
"}\n"
"")
        self.chat_data_text.setObjectName("chat_data_text")
        self.chat_with_who_notice = QtWidgets.QLabel(self.centralwidget)
        self.chat_with_who_notice.setGeometry(QtCore.QRect(290, 50, 341, 16))
        self.chat_with_who_notice.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));")
        self.chat_with_who_notice.setObjectName("chat_with_who_notice")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(850, 50, 20, 521))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(900, 60, 72, 15))
        self.label_3.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 9pt \"楷体\";")
        self.label_3.setObjectName("label_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 540, 991, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.images_label = QtWidgets.QLabel(self.centralwidget)
        self.images_label.setGeometry(QtCore.QRect(891, 140, 91, 91))
        self.images_label.setText("")
        self.images_label.setObjectName("images_label")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(870, 240, 131, 111))
        self.info_label.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 9pt \"楷体\";")
        self.info_label.setText("")
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.friend_list_update = QtWidgets.QPushButton(self.centralwidget)
        self.friend_list_update.setGeometry(QtCore.QRect(10, 20, 31, 28))
        self.friend_list_update.setStyleSheet("QPushButton{\n"
"    padding: 5px 25px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    color: #616161;\n"
"    font-weight: bold;\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    \n"
"    \n"
"}\n"
"QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
"    border: 2px solid transparent;\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
"    \n"
"    color: rgb(255, 79, 147);\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
"    color: #aeaeae;\n"
"    background-color:grey;\n"
"}")
        self.friend_list_update.setText("")
        self.friend_list_update.setObjectName("friend_list_update")
        self.delete_friend_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_friend_button.setGeometry(QtCore.QRect(430, 10, 121, 28))
        self.delete_friend_button.setStyleSheet("QPushButton{\n"
"    padding: 5px 25px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    color: #616161;\n"
"    font-weight: bold;\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    \n"
"    \n"
"}\n"
"QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
"    border: 2px solid transparent;\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
"    \n"
"    color: rgb(255, 79, 147);\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
"    color: #aeaeae;\n"
"    background-color:grey;\n"
"}")
        self.delete_friend_button.setObjectName("delete_friend_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "聊天系统"))
        __sortingEnabled = self.firend_list.isSortingEnabled()
        self.firend_list.setSortingEnabled(False)
        item = self.firend_list.item(0)
        item.setText(_translate("MainWindow", "好友A"))
        item = self.firend_list.item(1)
        item.setText(_translate("MainWindow", "好友B"))
        self.firend_list.setSortingEnabled(__sortingEnabled)
        self.all_chat_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#ff557f;\">欢迎进入聊天系统</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "我的好友"))
        self.add_friend_button.setText(_translate("MainWindow", "添加好友"))
        self.send_button.setText(_translate("MainWindow", "发送"))
        self.chat_with_who_notice.setText(_translate("MainWindow", "正在与XXX聊天..."))
        self.label_3.setText(_translate("MainWindow", "个人信息"))
        self.delete_friend_button.setText(_translate("MainWindow", "删除好友"))
